# -------------------------------
# General Site Settings
title: Recipe Rating Analysis
author: Hanlu Wu, Xiulin Chen
description: A data analysis project exploring recipe rating prediction.

# -------------------------------
# Build Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hanluwuum.github.io/recipe-rating-analysis/" # the base hostname & protocol for your site

markdown: kramdown
permalink: /:title/
paginate: 5
paginate_path: "/blog/page/:num"

# -------------------------------
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# -------------------------------
# Sections
sections:
  - name: Introduction
    content: >
      Welcome to our Recipe Rating Analysis project! This project explores how recipe features such as tags, preparation time, and reviews contribute to predicting recipe ratings. 
      Through machine learning techniques and careful analysis, we aim to uncover key insights that can help better understand user preferences.

  - name: Data Cleaning and Exploratory Data Analysis
    content: >
      The raw dataset contained missing values, duplicate entries, and inconsistent formatting. We cleaned the data by removing duplicates, handling missing values, and standardizing column formats.
      Exploratory analysis revealed interesting patterns, such as the correlation between preparation time and recipe ratings, as well as contributor trends and review sentiments.

  - name: Framing a Prediction Problem
    content: >
      The main goal of this analysis was to predict the rating of a recipe based on its features. Key predictors include tags, preparation time, number of steps, contributor reputation, and review sentiment.
      By defining this problem, we could focus on building models that leverage these predictors to make accurate and meaningful predictions.

  - name: Baseline Model
    content: >
      Our baseline model used a simple machine learning algorithm with two features: preparation time and number of steps. 
      While the performance was moderate, it provided a reference point to evaluate improvements from our final model.

  - name: Final Model
    content: >
      The final model incorporated engineered features such as review sentiment scores and contributor reputation. 
      After tuning hyperparameters and testing various algorithms, our final model achieved better performance and provided deeper insights into recipe rating patterns.

# -------------------------------
# Theme
theme: "minimal"
